title: Hello, world! I'm Maclxf
description: > # this means to ignore newlines until "baseurl:"
  Watch more! Think more! Do more!
permalink: ':title/'
baseurl: "/my_blog" # the subpath of your site, e.g. /blog
url: "http://maclxf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Maclxf # add your name
author-img: maclxf.jpg # add your photo
about-author: 多看！多想！多做！ # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: maclxf # add your Github handle
linkedin: # add your Linkedin handle
email: maclxf@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
